### PR TITLE
Option to view coordinates as hex

### PR DESCRIPTION
**Pull request by Atybot**
implements #26.
also any chances on getting the repo up to date?

### CODE REVIEW

**Comment by dimdenGD** [comment]
it won't get merged, because nobody needs that. If you need it you can just make OWOP script.

**Comment by nagalun** [comment]
ok lol just for that comment i'll do it sooner

**Comment by nagalun** [comment]
negative coords look funny but i'll let it slide for now

**Comment by dimdenGD** [comment]
lol.

**Pull request merged**
